### ISSUE TITLE
System Launcher crashed after use app

### ISSUE THREAD

**Issue by riceguardian** [Belmont-Gabriel/MIUI-11-XML-Vietnamese#1]
![Screenshot_2020-02-22-20-22-28-839_com miui bugreport](https://user-images.githubusercontent.com/61354010/75093892-988de180-55b8-11ea-8ac6-b60a4aa3bed4.jpg)

**Comment by trantuananh1996** [comment]
Ko phải vấn đề của gói ngôn ngữ
